#pragma once

#ifdef RGBLIGHT_ENABLE
    #define NOP_FUDGE 0.4
    #define WS2812_DI_PIN GP8
    #define RGBLIGHT_LED_COUNT 31
    #define RGBLIGHT_EFFECT_BREATHING
    #define RGBLIGHT_EFFECT_RAINBOW_MOOD
    #define RGBLIGHT_EFFECT_RAINBOW_SWIRL
    #define RGBLIGHT_EFFECT_ALTERNATING
#endif

#define DYNAMIC_KEYMAP_LAYER_COUNT 8