DEFERRED_EXEC_ENABLE = yes	
LTO_ENABLE = yes
VIA_ENABLE = yes

RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = ws2812
WS2812_DRIVER = vendor
VELOCIKEY_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = ssd1306
OLED_TIMEOUT = 0
OLED_TRANSPORT = i2c
WPM_ENABLE = yes

SRC += keyboard.c

OS_DETECTION_ENABLE = yes
EXTRAFLAGS += -flto